# -*- coding: utf-8 -*-
"""TASK 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kk_oRmaHdSV9amtr7YaSlpo8cdRuxpQh
"""

# Module 1 - Main Menu

students = {}

def main_menu():
    print("")
    print("UNIVERSITY STUDENT MANAGEMENT SYSTEM")
    print("")
    print("1. Add Student")
    print("2. Search Student")
    print("3. Update Student")
    print("4. Delete Student")
    print("5. Show All Students")
    print("6. Exit")
    print("")

main_menu()

# Module 2 - Add Student

def add_student():
    student_id = input("Enter Student ID : ")
    name = input("Enter Student Name : ")
    age = int(input("Enter Age : "))
    gender = input("Enter Gender : ")
    city = input("Enter City : ")

    matric = int(input("Enter Matric Marks : "))
    fsc = int(input("Enter FSc Marks : "))

    matric_percentage = (matric / 1100) * 100
    fsc_percentage = (fsc / 1100) * 100
    average_percentage = (matric_percentage + fsc_percentage) / 2

    if average_percentage >= 70:
        scholarship = "Eligible"
    else:
        scholarship = "Not Eligible"

    students[student_id] = {
        "name": name,
        "age": age,
        "gender": gender,
        "city": city,
        "matric": matric,
        "fsc": fsc,
        "average": average_percentage,
        "scholarship": scholarship
    }

    print("Student Added Successfully.")

add_student()

add_student()

# Module 3 - Search Student

def search_student():
    student_id = input("Enter Student ID : ")

    if student_id in students:
        s = students[student_id]

        print("==========================================")
        print("Student Found")
        print("==========================================")
        print("Student ID          :", student_id)
        print("Student Name        :", s["name"])
        print("Age                 :", s["age"])
        print("Gender              :", s["gender"])
        print("City                :", s["city"])
        print("Matric Marks        :", s["matric"])
        print("FSc Marks           :", s["fsc"])
        print("Average Percentage  :", format(s["average"], ".2f") + "%")
        print("Scholarship Status  :", s["scholarship"])
    else:
        print("Student Record Not Found.")

search_student()

# Module 4 - Update Student

def update_student():
    student_id = input("Enter Student ID : ")

    if student_id in students:
        matric = int(input("Enter New Matric Marks : "))
        fsc = int(input("Enter New FSc Marks : "))

        matric_percentage = (matric / 1100) * 100
        fsc_percentage = (fsc / 1100) * 100
        average_percentage = (matric_percentage + fsc_percentage) / 2

        if average_percentage >= 70:
            scholarship = "Eligible"
        else:
            scholarship = "Not Eligible"

        students[student_id]["matric"] = matric
        students[student_id]["fsc"] = fsc
        students[student_id]["average"] = average_percentage
        students[student_id]["scholarship"] = scholarship

        print("Student Record Updated Successfully.")
    else:
        print("Student Record Not Found.")

# Module 5 - Delete Student

def delete_student():
    student_id = input("Enter Student ID : ")

    if student_id in students:
        del students[student_id]
        print("Student Record Deleted Successfully.")
    else:
        print("Student Record Not Found.")

# Module 6 - Show All Students

def show_all_students():
    if len(students) == 0:
        print("No Student Records Available.")
    else:
        print("==========================================")
        print("STUDENT LIST")
        print("==========================================")

        for student_id, s in students.items():
            print("ID                 :", student_id)
            print("Name               :", s["name"])
            print("Average Percentage :", format(s["average"], ".2f") + "%")
            print("Scholarship        :", s["scholarship"])
            print("------------------------------------------")

show_all_students()

# Module 7 - Exit

def exit_message():
    print("==========================================")
    print("Thank You for Using")
    print("University Student Management System")
    print("==========================================")

# Run Program

while True:
    main_menu()
    choice = input("Enter Choice : ")

    if choice == "1":
        add_student()

    elif choice == "2":
        search_student()

    elif choice == "3":
        update_student()

    elif choice == "4":
        delete_student()

    elif choice == "5":
        show_all_students()

    elif choice == "6":
        exit_message()
        break

    else:
        print("Invalid Choice. Please try again.")

#Challenge 01
students ={}

print(students)

#Challenge 03
def search_by_name():
    name = input("Enter Student Name : ")

    found = False

    for student_id, s in students.items():
        if s["name"].lower() == name.lower():
            print("Student ID :", student_id)
            print("Student Name :", s["name"])
            print("Average Percentage :", format(s["average"], ".2f") + "%")
            found = True

    if found == False:
        print("Student Record Not Found.")

#Challenge 05
confirm = input("Are you sure you want to delete this student? (Y/N) : ")

if confirm == "Y" or confirm == "y":
    del students[student_id]
    print("Student Record Deleted Successfully.")
else:
    print("Delete Cancelled.")